---
- hosts: localhost
  gather_facts: false
  become: false

  tasks:
  - add_host: name="master.{{ id }}.demo.li9.com" groups=openshift ansible_user=ec2-user
  - add_host: name="app1.{{ id }}.demo.li9.com" groups=openshift ansible_user=ec2-user
  - add_host: name="app2.{{ id }}.demo.li9.com" groups=openshift ansible_user=ec2-user

- hosts: openshift
  become: true
  gather_facts: true
  vars_files:
  - vars.yaml
  tasks:

  - set_fact:
      master: "master.{{id}}.demo.li9.com"
      app1:   "app1.{{id}}.demo.li9.com"
      app2:   "app2.{{id}}.demo.li9.com"

  - name: Change /etc/hosts
    template: src=templates/etc.hosts.j2 dest=/etc/hosts

  - name: Install required packages
    yum: name={{item}} state=latest
    with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - yum-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct

  - name: Updating system to the latest versions
    yum: name=* state=latest

  - name: Remove cloud-init
    yum: name=cloud-init state=absent

  - name: Set hostname
    hostname: name={{inventory_hostname}}

  - name: Register on redhat
    redhat_subscription:
      state: present
      username: "{{redhat_username}}"
      password: "{{redhat_password}}"
      pool_ids:
        - 8a85f98c6096a56d0160981ff96615c1

  - name: Disable repos
    command: subscription-manager repos --disable="*"

  - name: Disable remaining
    command: yum-config-manager --disable \*

  - name: Enable repos
    command: |
      subscription-manager repos
      --enable="rhel-7-server-rpms"
      --enable="rhel-7-server-extras-rpms"
      --enable="rhel-7-server-ose-3.11-rpms"
      --enable="rhel-7-server-ansible-2.6-rpms"

  - name: Install docker and supporting packages
    yum: name={{item}} state=latest
    with_items:
    - docker
    - skopeo

  - name: Start and enable docker
    service: name=docker state=started enabled=true

- hosts: master.{{id}}.demo.li9.com
  become: true
  gather_facts: false
  vars_files:
  - vars.yaml
  tasks:


  - name: Install openshift-ansible
    yum: name=openshift-ansible state=latest

  - name: Copy ansible inventory
    template: src=templates/etc.ansible.hosts.j2 dest=/etc/ansible/hosts

  - name: Configure ansible.cfg
    template: src=templates/ansible.cfg.j2 dest=/etc/ansible/ansible.cfg

  - name: Check if SSH key exists
    stat: path=/root/.ssh/id_rsa
    register: stat_id_rsa

  - name: Generate new SSH key
    command: ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa
    when: stat_id_rsa.stat.exists == False 

  - name: Save public key
    command: cat /root/.ssh/id_rsa.pub
    register: ssh_public_key

  - name: Show public key
    debug: var=ssh_public_key.stdout

  - name: Save public key
    add_host:
      name: keydata
      ssh_public_key: "{{ssh_public_key.stdout}}"

- hosts: openshift
  become: true
  gather_facts: false
  tasks:

  - name: Configure ssh authorized keys
    copy: dest=/root/.ssh/authorized_keys content="{{ hostvars['keydata']['ssh_public_key']}}"



